# MANDATORY: The location to save downloaded pages to.
save_location = '~/confluence_downloads'

# OPTIONAL: The location to save the history file to. Defaults to the same as save_location
history_location = '~/confluence_downloads'

# OPTIONAL: Always sync the page automatically on editor exit without asking. Defaults to false
auto_sync = 'false'

# OPTIONAL: The editor to open the markdown file in. Defaults to vim
[editor]
# Cmd used to open the editor
editor = 'nvim'
# OPTIONAL: Arguments for the editor (page size, spell check etc). Defaults to none
# Ensure each flag is a separate list item as below
args = ["-c", "set columns=120", "-c", "set linebreak", "-c", "set spell"]

# MANDATORY: api stores the api access information for confluence
[api]
# The domain of your confluence instance (i.e. https://<your-domain>/wiki/...)
confluence_domain = 'exampledomain.atlassian.net'

# Your confluence username
username = 'example@exampledomain.com'

# Your confluence API token
token = '<encoded token>'

# OPTIONAL: The label to select spaces by. Defaults to all global spaces if none set
label = 'api'
