# MANDATORY: The location to save downloaded pages to.
# save_location = '~/confluence_downloads'

# MANDATORY: Key stores the api access information for confluence
# [key]
## The domain of your confluence instance (i.e. https://<your-domain>/wiki/...)
# confluence_domain = ''
## Your confluence username
# username = 
## Your confluence API token
#token = ''
